/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
        String signupName;
        String signupBalance;
        String signupAccNo;
        String signupCardNo;
        String signupPIN;
        String signupEmail;
        String signupMobileno;
    public Login() {
        initComponents();
    }
    public Login (String signupName,String signupBalance ,String signupAccNo,String signupCardNo,String signupPIN,String signupEmail,String signupMobileno){
        this.signupName = signupName;
        this.signupBalance = signupBalance;
        this.signupAccNo =  signupAccNo;
        this.signupCardNo = signupCardNo;
        this.signupPIN = signupPIN;
        this.signupEmail = signupEmail;
        this.signupMobileno = signupMobileno;
        //String a=signupName;
        System.out.println(this.signupName + " : " + this.signupEmail + " : ");
        
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JOptionPane = new javax.swing.JOptionPane();
        Wel2ATMlab = new javax.swing.JLabel();
        Cardnolab = new javax.swing.JLabel();
        PINlab = new javax.swing.JLabel();
        CardnoTextField = new javax.swing.JTextField();
        LOGINButton = new javax.swing.JButton();
        CLEARButton = new javax.swing.JButton();
        SIGNUPButton = new javax.swing.JButton();
        PINPasswordField = new javax.swing.JPasswordField();

        JOptionPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JOptionPane.setFocusTraversalPolicyProvider(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Wel2ATMlab.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Wel2ATMlab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Wel2ATMlab.setText("Welcome to ATM");

        Cardnolab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cardnolab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Cardnolab.setText("Card No:");

        PINlab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PINlab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PINlab.setText("PIN:");

        CardnoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardnoTextFieldActionPerformed(evt);
            }
        });

        LOGINButton.setText("LOG IN");
        LOGINButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGINButtonActionPerformed(evt);
            }
        });

        CLEARButton.setText("CLEAR");
        CLEARButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARButtonActionPerformed(evt);
            }
        });

        SIGNUPButton.setText("CREATE ACC");
        SIGNUPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIGNUPButtonActionPerformed(evt);
            }
        });

        PINPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PINPasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Wel2ATMlab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PINlab, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cardnolab, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SIGNUPButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LOGINButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(CLEARButton))
                            .addComponent(CardnoTextField)
                            .addComponent(PINPasswordField))
                        .addGap(0, 300, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Wel2ATMlab)
                        .addGap(18, 18, 18)
                        .addComponent(Cardnolab))
                    .addComponent(CardnoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PINlab)
                    .addComponent(PINPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LOGINButton)
                    .addComponent(CLEARButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SIGNUPButton)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CardnoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardnoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardnoTextFieldActionPerformed

    private void LOGINButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGINButtonActionPerformed
        // TODO add your handling code here:
        String cardNo = CardnoTextField.getText();
    // Retrieve the text from the password field
    String password = new String(PINPasswordField.getPassword());

    // Now you can use 'cardNo' and 'password' as needed
    if(cardNo.equals(this.signupCardNo) && password.equals(this.signupPIN)){
        // Login successful
        System.out.println(this.signupName + " : " + this.signupEmail + " : ");
        Transactionpage data = new Transactionpage(signupName, signupBalance , signupAccNo, signupCardNo,signupPIN,signupEmail,signupMobileno);
        data.setVisible(true);
        setVisible(false);
        
    } else {
        // Invalid credentials
        JOptionPane.showMessageDialog(this, "Invalid Credentials");
    }
    }//GEN-LAST:event_LOGINButtonActionPerformed

    private void CLEARButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARButtonActionPerformed
        // TODO add your handling code here:
        // Clear the text field
    CardnoTextField.setText("");
    // Clear the password field
    PINPasswordField.setText("");
    }//GEN-LAST:event_CLEARButtonActionPerformed

    private void SIGNUPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIGNUPButtonActionPerformed
        // TODO add your handling code here:
        // Retrieve the text from the text field
        Signup CreateAcc = new Signup();
        CreateAcc.setVisible(true);
        setVisible(false);
    
    }//GEN-LAST:event_SIGNUPButtonActionPerformed

    private void PINPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PINPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PINPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLEARButton;
    private javax.swing.JTextField CardnoTextField;
    private javax.swing.JLabel Cardnolab;
    public javax.swing.JOptionPane JOptionPane;
    private javax.swing.JButton LOGINButton;
    private javax.swing.JPasswordField PINPasswordField;
    private javax.swing.JLabel PINlab;
    private javax.swing.JButton SIGNUPButton;
    private javax.swing.JLabel Wel2ATMlab;
    // End of variables declaration//GEN-END:variables
}
