/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class Transactionpage extends javax.swing.JFrame {

    /**
     * Creates new form Transactionpage
     */
        String signupName;
        String signupBalance;
        String signupAccNo;
        String signupCardNo;
        String signupPIN;
        String signupEmail;
        String signupMobileno;
    public Transactionpage() {
        initComponents();
    }
    public Transactionpage (String signupName,String signupBalance ,String signupAccNo,String signupCardNo,String signupPIN,String signupEmail,String signupMobileno){
        this.signupName = signupName;
        this.signupBalance = signupBalance;
        this.signupAccNo =  signupAccNo;
        this.signupCardNo = signupCardNo;
        this.signupPIN = signupPIN;
        this.signupEmail = signupEmail;
        this.signupMobileno = signupMobileno;
        System.out.println(this.signupName + " : " + this.signupEmail + "This is Transction Page");
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Deposit = new javax.swing.JButton();
        FastCash = new javax.swing.JButton();
        PINChange = new javax.swing.JButton();
        CashWithdrawl = new javax.swing.JButton();
        MiniStatement = new javax.swing.JButton();
        BalanceEnquiry = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Please Select Your Transaction");

        Deposit.setText("Deposit");
        Deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositActionPerformed(evt);
            }
        });

        FastCash.setText("Fast Cash");
        FastCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FastCashActionPerformed(evt);
            }
        });

        PINChange.setText("PIN Change");
        PINChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PINChangeActionPerformed(evt);
            }
        });

        CashWithdrawl.setText("Cash Withdrawl");
        CashWithdrawl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashWithdrawlActionPerformed(evt);
            }
        });

        MiniStatement.setText("Mini Statement");
        MiniStatement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiniStatementActionPerformed(evt);
            }
        });

        BalanceEnquiry.setText("Balance Enquiry");
        BalanceEnquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceEnquiryActionPerformed(evt);
            }
        });

        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PINChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FastCash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Deposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CashWithdrawl)
                                    .addComponent(BalanceEnquiry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(MiniStatement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(1, 1, 1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(EXIT)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deposit)
                    .addComponent(CashWithdrawl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FastCash)
                    .addComponent(MiniStatement))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PINChange)
                    .addComponent(BalanceEnquiry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(EXIT)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositActionPerformed
        // TODO add your handling code here:
        Deposit data = new Deposit(this.signupBalance);
        data.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_DepositActionPerformed

    private void FastCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FastCashActionPerformed
        // TODO add your handling code here:
        Fastcash data = new Fastcash(this.signupBalance);
        data.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_FastCashActionPerformed

    private void MiniStatementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiniStatementActionPerformed
        // TODO add your handling code here:
        Ministatement data = new Ministatement(signupName,signupBalance ,signupAccNo,signupCardNo,signupPIN,signupEmail,signupMobileno);
        data.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_MiniStatementActionPerformed

    private void BalanceEnquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceEnquiryActionPerformed
        // TODO add your handling code here:
        BalanceEnqury data = new BalanceEnqury(this.signupBalance);
        data.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BalanceEnquiryActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EXITActionPerformed

    private void CashWithdrawlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashWithdrawlActionPerformed
        // TODO add your handling code here:
        System.out.println(" This is Balance page "+this.signupBalance );
        CashWithdrawl data = new CashWithdrawl(this.signupBalance);
        data.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_CashWithdrawlActionPerformed

    private void PINChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PINChangeActionPerformed
        // TODO add your handling code here:
        PINchange data =new PINchange(this.signupPIN);
        data.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_PINChangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transactionpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transactionpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transactionpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transactionpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transactionpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BalanceEnquiry;
    private javax.swing.JButton CashWithdrawl;
    private javax.swing.JButton Deposit;
    private javax.swing.JButton EXIT;
    private javax.swing.JButton FastCash;
    private javax.swing.JButton MiniStatement;
    private javax.swing.JButton PINChange;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
